name: www.helloamericatheworldiswatching.com
favicon: null
layout_spectrum: 0.5988523112609982
typography_spectrum: 0.4415582858491689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3d3d'
    - '#fc0016'
    - '#fefefe'
    - '#111111'
    - '#a2a2a2'
  brandStrength: 0.3125
  lightness: 0.6321303432341665
  saturation: 0.2829397297464311
  rhythmicContrast: 0.37416144483722746
purpose: []
